name: Build and Publish Design Tokens

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

      - name: Run linting
        run: npm run lint

      - name: Build design tokens
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: design-tokens-dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Build design tokens
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # TODO: Dodaj job dla integracji z Figmą:
  # figma-sync:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
  #   steps:
  #   - name: Sync tokens from Figma
  #     # Użyj figma-to-code-cli lub custom script
  #   - name: Create PR with updated tokens
  #     # Automatycznie stwórz PR z nowymi tokenami
